version: "3"
services:
  app:
    container_name: trait-seeker
    image: trait-seeker:v2
    build:
      context: ../
      dockerfile: docker/Dockerfile
      args:
        environment: dev
        status: stable
    ports:
        - 8001:8001
